services:
  - type: web
    name: cyon-jalingo
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate && python manage.py createsuperuser --noinput || true
    startCommand: gunicorn cyon_project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: cyon-db
          property: connectionString
      - key: DJANGO_SUPERUSER_USERNAME
        value: lanwebanu
      - key: DJANGO_SUPERUSER_EMAIL
        value: alexlanweanthony@gmail.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: Lanweanthony@#3456

databases:
  - name: cyon-db
    databaseName: cyon
    user: cyon_user
    plan: free
