# Generated by Django 6.0.7 on 2026-07-14 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt', null=True)),
            ],
            options={
                'db_table': 'admins',
            },
        ),
        migrations.CreateModel(
            name='DiocesanAccount',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('denary', models.CharField(max_length=100, unique=True)),
                ('diocese_name', models.CharField(db_column='dioceseName', max_length=255)),
                ('account_holder_name', models.CharField(db_column='accountHolderName', max_length=255)),
                ('account_number', models.CharField(db_column='accountNumber', max_length=50)),
                ('bank_name', models.CharField(db_column='bankName', max_length=100)),
                ('swift_code', models.CharField(blank=True, db_column='swiftCode', max_length=50, null=True)),
                ('routing_number', models.CharField(blank=True, db_column='routingNumber', max_length=50, null=True)),
                ('currency', models.CharField(blank=True, default='USD', max_length=10, null=True)),
                ('is_active', models.BooleanField(blank=True, db_column='isActive', default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt', null=True)),
                ('sort_code', models.CharField(blank=True, db_column='sortCode', max_length=50, null=True)),
            ],
            options={
                'db_table': 'diocesan_accounts',
            },
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('achievement', models.TextField()),
                ('photo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'leaders',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('denary', models.CharField(max_length=100)),
                ('parish', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('address', models.TextField()),
                ('occupation', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, default='pending', max_length=50, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_column='submittedAt', null=True)),
            ],
            options={
                'db_table': 'registrations',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('denary', models.CharField(max_length=100)),
                ('parish', models.CharField(blank=True, max_length=255, null=True)),
                ('event_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, db_column='uploaded_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cyon.admin')),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='EventMedia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('original_name', models.CharField(db_column='original_name', max_length=255)),
                ('mime_type', models.CharField(db_column='mime_type', max_length=100)),
                ('file_path', models.CharField(db_column='file_path', max_length=255)),
                ('file_size', models.IntegerField(db_column='file_size')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='cyon.event')),
            ],
            options={
                'db_table': 'event_media',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(blank=True, default='USD', max_length=10, null=True)),
                ('payment_method', models.CharField(db_column='paymentMethod', max_length=50)),
                ('card_last_four', models.CharField(blank=True, db_column='cardLastFour', max_length=10, null=True)),
                ('cardholder_name', models.CharField(blank=True, db_column='cardholderName', max_length=255, null=True)),
                ('email', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, default='completed', max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, db_column='transactionId', max_length=100, null=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True, db_column='paidAt', null=True)),
                ('registration', models.ForeignKey(blank=True, db_column='registrationId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cyon.registration')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
